### ISSUE TITLE
Not building on RPi2 - Raspbian and Nodejs 0.12.0

### ISSUE THREAD

**Issue by samueljmurray** [lperrin/node_airtunes#33]
These are the errors output but npm:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/airtunes
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.18.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airtunes"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! airtunes@0.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airtunes@0.1.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the airtunes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls airtunes
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

It seems to be an issue with Nodejs 0.12.0 as I've managed to install successfully with Nodejs 0.10.36

**Comment by WeeJeWel** [comment]
+1

**Comment by marcokeur** [comment]
Had the same problems, and looking at it at the moment. It seems that the V8 api has had a major overhaul with many breaking changes. I've made some modifications to the cpp lib and it seems to work now. Will do some more testing, but thing i'm there!
