### ISSUE TITLE
node-gyp build: several errors

### ISSUE THREAD

**Issue by loretoparisi** [lperrin/node_airtunes#42]
I get several errors when doing a build

``` shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.2.6 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/MacHDD2/Developmemt/Javascript/node_airtunes/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/admin/.node-gyp/4.2.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/admin/.node-gyp/4.2.6',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/MacHDD2/Developmemt/Javascript/node_airtunes',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
2016-06-17 10:29:52.386 xcodebuild[13957:8044310] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/airtunes/src/codec.o
../src/codec.cc:59:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/codec.cc:62:11: error: no member named 'Dispose' in 'v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >'
  wrapper.Dispose();
  ~~~~~~~ ^
../src/codec.cc:67:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> NewEncoder(const Arguments& args) {
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/codec.cc:68:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/codec.cc:78:98: error: too few arguments to function call, expected 2, have 1
  Persistent<ObjectTemplate> encoderClass = Persistent<ObjectTemplate>::New(ObjectTemplate::New());
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:639:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/admin/.node-gyp/4.2.6/include/node/v8config.h:301:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/codec.cc:78:73: error: 'New' is a private member of 'v8::PersistentBase<v8::ObjectTemplate>'
  Persistent<ObjectTemplate> encoderClass = Persistent<ObjectTemplate>::New(ObjectTemplate::New());
                                                                        ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:639:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/codec.cc:79:15: error: member reference type 'Persistent<v8::ObjectTemplate>' is not a pointer; did you mean to use '.'?
  encoderClass->SetInternalFieldCount(1);
  ~~~~~~~~~~~~^~
              .
../src/codec.cc:79:17: error: no member named 'SetInternalFieldCount' in 'v8::Persistent<v8::ObjectTemplate, v8::NonCopyablePersistentTraits<v8::ObjectTemplate> >'
  encoderClass->SetInternalFieldCount(1);
  ~~~~~~~~~~~~  ^
../src/codec.cc:80:62: error: member reference type 'Persistent<v8::ObjectTemplate>' is not a pointer; did you mean to use '.'?
  Persistent<Object> o = Persistent<Object>::New(encoderClass->NewInstance());
                                                 ~~~~~~~~~~~~^~
                                                             .
../src/codec.cc:80:64: error: no member named 'NewInstance' in 'v8::Persistent<v8::ObjectTemplate, v8::NonCopyablePersistentTraits<v8::ObjectTemplate> >'
  Persistent<Object> o = Persistent<Object>::New(encoderClass->NewInstance());
                                                 ~~~~~~~~~~~~  ^
../src/codec.cc:80:46: error: 'New' is a private member of 'v8::PersistentBase<v8::Object>'
  Persistent<Object> o = Persistent<Object>::New(encoderClass->NewInstance());
                                             ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:639:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/codec.cc:81:4: error: member reference type 'Persistent<v8::Object>' is not a pointer; did you mean to use '.'?
  o->SetPointerInInternalField(0, encoder);
  ~^~
   .
../src/codec.cc:81:6: error: no member named 'SetPointerInInternalField' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
  o->SetPointerInInternalField(0, encoder);
  ~  ^
../src/codec.cc:82:5: error: no member named 'MakeWeak' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
  o.MakeWeak(encoder, encoder_weak_callback);
  ~ ^
../src/codec.cc:84:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(o);
         ~~~~~ ^
../src/codec.cc:87:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> EncodeALAC(const Arguments& args) {
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/codec.cc:88:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/codec.cc:90:10: error: member access into incomplete type 'const v8::internal::Arguments'
  if(args.Length() < 4) {
         ^
/Users/admin/.node-gyp/4.2.6/include/node/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/codec.cc:92:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Null());
           ~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/airtunes/src/codec.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Volumes/MacHDD2/Developmemt/Javascript/node_airtunes
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by loretoparisi** [comment]
Could it be related to `eslint` as exaplained [here](https://github.com/eslint/eslint/issues/4760)?

**Comment by LukeTim** [comment]
Hi, @loretoparisi, did you ever resolve this?

I am getting the same errors.
